/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-08-22 10:02:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.freeBoard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.team3.freeBoard.model.vo.*;
import com.kh.team3.member.model.vo.*;

public final class boardDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/freeBoard/../common/menubar.jsp", Long.valueOf(1629537078886L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.kh.team3.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.kh.team3.freeBoard.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");

	Board b = (Board)request.getAttribute("b");
	Member loginUser = (Member)session.getAttribute("loginUser");

      out.write("  \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	.outer{\r\n");
      out.write("		width:800px;\r\n");
      out.write("		height:500px;\r\n");
      out.write("		margin:auto;\r\n");
      out.write("		margin-top:50px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	.outer>table{\r\n");
      out.write("		width:100%;\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.outer>table p{\r\n");
      out.write("		height:230px;\r\n");
      out.write("		margin:0;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.replyArea{\r\n");
      out.write("		width:800px;\r\n");
      out.write("		color:white;\r\n");
      out.write("		background:dimgray;\r\n");
      out.write("		margin:auto;\r\n");
      out.write("	}\r\n");
      out.write("	#addReply{\r\n");
      out.write("		color:white;\r\n");
      out.write("		background:gray;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	table {\r\n");
      out.write("    	width: 100%;\r\n");
      out.write("    	border-bottom: 1px solid #444444;\r\n");
      out.write("    	border-collapse: collapse;\r\n");
      out.write("  	}\r\n");
      out.write("  \r\n");
      out.write("	/* 글 내용의 경계선 표시 */\r\n");
      out.write("	.content{\r\n");
      out.write("		border: 1px dotted #cecece;\r\n");
      out.write("	}\r\n");
      out.write("	/* 글 내용안에 있는 이미지의 크기 제한 */\r\n");
      out.write("	.content img{\r\n");
      out.write("		max-width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	/* 댓글에 관련된 css */\r\n");
      out.write("	.comments ul{\r\n");
      out.write("		padding: 0;\r\n");
      out.write("		margin: 0;\r\n");
      out.write("		list-style-type: none;\r\n");
      out.write("	}\r\n");
      out.write("	.comments ul li{\r\n");
      out.write("		border-top: 1px solid #888; /* li 의 윗쪽 경계선 */\r\n");
      out.write("	}\r\n");
      out.write("	.comments dt{\r\n");
      out.write("		margin-top: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	.comments dd{\r\n");
      out.write("		margin-left: 26px;\r\n");
      out.write("	}\r\n");
      out.write("	.comments form textarea, .comments form button{\r\n");
      out.write("		float: left;\r\n");
      out.write("	}\r\n");
      out.write("	.comments li{\r\n");
      out.write("		clear: left;\r\n");
      out.write("	}\r\n");
      out.write("	.comments form textarea{\r\n");
      out.write("		width: 85%;\r\n");
      out.write("		height: 80px;\r\n");
      out.write("	}\r\n");
      out.write("	.comments form button{\r\n");
      out.write("		width: 15%;\r\n");
      out.write("		height: 80px;\r\n");
      out.write("	}\r\n");
      out.write("	/* 댓글에 댓글을 다는 폼과 수정폼을 일단 숨긴다. */\r\n");
      out.write("	.comment form{\r\n");
      out.write("		display: none;\r\n");
      out.write("	}\r\n");
      out.write("	.comment{\r\n");
      out.write("		position: relative;\r\n");
      out.write("	}\r\n");
      out.write("	.comment .reply_icon{\r\n");
      out.write("		width: 8px;\r\n");
      out.write("		height: 8px;\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		top: 10px;\r\n");
      out.write("		left: 30px;\r\n");
      out.write("	}\r\n");
      out.write("	.comments .user-img{\r\n");
      out.write("		width: 20px;\r\n");
      out.write("		height: 20px;\r\n");
      out.write("		border-radius: 50%;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"resources\\css\\common.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"resources\\css\\main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources\\css\\common.css\">\r\n");
      out.write("<script src=\"resources\\js\\jquery.js\"></script>\r\n");
      out.write("<script src=\"resources\\js\\common.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"header-wrap\">\r\n");
      out.write("\r\n");
      out.write("      <header class=\"header-inner\">\r\n");
      out.write("         <h1>\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("            <picture>\r\n");
      out.write("                        <source media=\"(max-width:800px)\" srcset=\"resources\\images\\common\\logo-white.png\">\r\n");
      out.write("                        <img src=\"resources\\images\\common\\logo.jpg\" alt=\"사구팔구\">\r\n");
      out.write("            </picture>\r\n");
      out.write("            </a>\r\n");
      out.write("         </h1>\r\n");
      out.write("         <p class=\"mobile-menu-open\">\r\n");
      out.write("            <button>\r\n");
      out.write("                        <span class=\"blind\">메뉴 열기</span>\r\n");
      out.write("                        <span></span>\r\n");
      out.write("                        <span></span>\r\n");
      out.write("                        <span></span>\r\n");
      out.write("            </button>\r\n");
      out.write("         </p>\r\n");
      out.write("         <div class=\"mobile-menu-wrap\">\r\n");
      out.write("            <div class=\"mobile-menu-scroll\">\r\n");
      out.write("               <ul class=\"site-choice\">\r\n");
      out.write("            \r\n");
      out.write("               </ul>\r\n");
      out.write("               <ul class=\"util-menu\">\r\n");
      out.write("                  <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                  <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/MyPageMove.me\">마이 페이지</a></li>\r\n");
      out.write("                  <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mystore.ms\">내 상점</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("               <nav id=\"gnb\">\r\n");
      out.write("                  <h2 class=\"blind\">메인메뉴</h2>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                     <li class=\"m1\">\r\n");
      out.write("                     	<a href=\"");
      out.print(request.getContextPath());
      out.write("/Notice_USER.NU\">공지사항</a>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"m2\">\r\n");
      out.write("                        <a href=\"#\">거래장터</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/exchangeServlet.es\">챗</a></li>\r\n");
      out.write("                           <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/sellDetail.bo\">판매 게시판</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"m3\">\r\n");
      out.write("                        <a href=\"#\">커뮤니티</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li><a href=\"#\">무료나눔</a></li>\r\n");
      out.write("                           <li><a href=\"list.bo\">자유 게시판</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"m4 no-sub\">\r\n");
      out.write("                                 <a href=\"#\">기타</a>\r\n");
      out.write("                                 <ul>\r\n");
      out.write("                                    <li><a href=\"#\">이벤트</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">신고/문의</a></li>                    \r\n");
      out.write("                                 </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p class=\"mobile-menu-close\">\r\n");
      out.write("               <button>\r\n");
      out.write("                  <span class=\"blind\">메뉴닫기</span>\r\n");
      out.write("                  <span></span>\r\n");
      out.write("                  <span></span>\r\n");
      out.write("               </button>\r\n");
      out.write("            </p>\r\n");
      out.write("         </div>\r\n");
      out.write("      </header>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"outer\">\r\n");
      out.write("		<br>\r\n");
      out.write("		\r\n");
      out.write("		<h2>자유 게시판</h2>\r\n");
      out.write("		<br>\r\n");
      out.write("		\r\n");
      out.write("		<table align=\"center\">\r\n");
      out.write("			\r\n");
      out.write("			<tr>\r\n");
      out.write("				\r\n");
      out.write("				 \r\n");
      out.write("				<th width=\"10%\">[");
      out.print( b.getCategoryNo() );
      out.write("]</th>\r\n");
      out.write("				<th colspan=\"2\" align=\"left\">");
      out.print( b.getBoardTitle() );
      out.write("</th>\r\n");
      out.write("				\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td rowspan=\"2\" height=\"100\">프로필사진</td>\r\n");
      out.write("				<th width=\"100\" colspan=\"2\" height=\"70\" align=\"left\">");
      out.print( b.getUserId() );
      out.write("</th>\r\n");
      out.write("				\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>");
      out.print( b.getCreateDate() );
      out.write("</td>\r\n");
      out.write("				<td align=\"right\">조회수 : ");
      out.print( b.getBoardCount() );
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><p>");
      out.print( b.getBoardContent() );
      out.write("</p></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<div class=\"btns\" align=\"right\">\r\n");
      out.write("			<button type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/list.bo?currentPage=1';\">목록으로</button>\r\n");
      out.write("			\r\n");
      out.write("			");
 if(loginUser != null && loginUser.getUserId().equals(b.getUserId())){ 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				<button type=\"button\" onclick=\"updateForm();\">수정하기</button>\r\n");
      out.write("				<button type=\"button\" onclick=\"deleteBoard();\">삭제하기</button>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<form action=\"\" id=\"postForm\" method=\"post\">\r\n");
      out.write("			<input type=\"hidden\" name=\"bno\" value=\"");
      out.print( b.getBoardNo() );
      out.write("\">\r\n");
      out.write("		</form>\r\n");
      out.write("		<script>\r\n");
      out.write("			function updateForm(){\r\n");
      out.write("				$(\"#postForm\").attr(\"action\", \"");
      out.print(request.getContextPath());
      out.write("/updateForm.bo\");\r\n");
      out.write("				$(\"#postForm\").submit();\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			function deleteBoard(){\r\n");
      out.write("				$(\"#postForm\").attr(\"action\", \"");
      out.print(request.getContextPath());
      out.write("/deleteB.bo\");\r\n");
      out.write("				$(\"#postForm\").submit();\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("		<br>\r\n");
      out.write("			<div class=\"comments\">\r\n");
      out.write("		<!-- 원글에 댓글을 작성할 수 있는 폼 -->\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"comment_form\">\r\n");
      out.write("			<form action=\"comment_insert.do\" method=\"post\"> \r\n");
      out.write("			<!-- 댓글의 그룹번호는 원글의 글번호가 된다. -->\r\n");
      out.write("				<input type=\"hidden\" name=\"ref_group\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("			<!-- 댓글의 대상자는 원글의 작성자가 된다. -->\r\n");
      out.write("				<input type=\"hidden\" name=\"target_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.writer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("				<textarea name=\"content\"></textarea>\r\n");
      out.write("				<button type=\"submit\">등록</button>\r\n");
      out.write("            </form>\r\n");
      out.write("            \r\n");
      out.write("		</div>\r\n");
      out.write("   	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
