/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-08-25 11:45:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.kh.team3.eventBoard.model.vo.*;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/common/center.jsp", Long.valueOf(1629881450571L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1629818110321L));
    _jspx_dependants.put("/views/common/menubar.jsp", Long.valueOf(1629818111407L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.kh.team3.eventBoard.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\r\n");
      out.write("<title> 4989 | HOME </title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("  ");
  
    String path = (String)request.getSession().getAttribute("path");

      out.write("\r\n");
      out.write("  ");
   
  	
   String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"resources\\css\\common.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"resources\\css\\main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources\\css\\common.css\">\r\n");
      out.write("<script src=\"resources\\js\\jquery.js\"></script>\r\n");
      out.write("<script src=\"resources\\js\\common.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"header-wrap\">\r\n");
      out.write("\r\n");
      out.write("      <header class=\"header-inner\">\r\n");
      out.write("         <h1>\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("            <picture>\r\n");
      out.write("                        <source media=\"(max-width:800px)\" srcset=\"resources\\images\\common\\logo-white.png\">\r\n");
      out.write("                        <img src=\"resources\\images\\common\\logo.jpg\" alt=\"사구팔구\">\r\n");
      out.write("            </picture>\r\n");
      out.write("            </a>\r\n");
      out.write("         </h1>\r\n");
      out.write("         <p class=\"mobile-menu-open\">\r\n");
      out.write("            <button>\r\n");
      out.write("                        <span class=\"blind\">메뉴 열기</span>\r\n");
      out.write("                        <span></span>\r\n");
      out.write("                        <span></span>\r\n");
      out.write("                        <span></span>\r\n");
      out.write("            </button>\r\n");
      out.write("         </p>\r\n");
      out.write("         <div class=\"mobile-menu-wrap\">\r\n");
      out.write("            <div class=\"mobile-menu-scroll\">\r\n");
      out.write("               <ul class=\"site-choice\">\r\n");
      out.write("            \r\n");
      out.write("               </ul>\r\n");
      out.write("               <ul class=\"util-menu\">\r\n");
      out.write("                  <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/main.me\">Home</a></li>\r\n");
      out.write("                  <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/MyPageMove.me\">마이 페이지</a></li>\r\n");
      out.write("                  <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/mystore.ms\">내 상점</a></li>\r\n");
      out.write("                  <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/logout.me\">로그아웃</a></li>\r\n");
      out.write("              	    <li>  <img src=\"");
      out.print(contextPath);
      out.write("/resources/board_upfiles/");
      out.print( path );
      out.write("\" width=\"30px\" height=\"30px\"> </li>\r\n");
      out.write("               </ul>\r\n");
      out.write("               <nav id=\"gnb\">\r\n");
      out.write("                  <h2 class=\"blind\">메인메뉴</h2>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                     <li class=\"m1\">\r\n");
      out.write("                     	<a href=\"");
      out.print(request.getContextPath());
      out.write("/Notice_Manager.NM\">공지사항</a>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"m2\">\r\n");
      out.write("                        <a href=\"#\">거래장터</a>\r\n");
      out.write("                        <ul >\r\n");
      out.write("                           <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/exchangeServlet.es\">물물교환 게시판</a></li>\r\n");
      out.write("                           <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/sellList.bo\">판매 게시판</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"m3\">\r\n");
      out.write("                        <a href=\"#\">커뮤니티</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li><a href=\"#\">무료나눔</a></li>\r\n");
      out.write("                           <li><a href=\"list.bo\">자유 게시판</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"m4 no-sub\">\r\n");
      out.write("                                 <a href=\"#\">기타</a>\r\n");
      out.write("                                 <ul>\r\n");
      out.write("                                     <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/event.bo\">이벤트</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">신고/문의</a></li>                    \r\n");
      out.write("                                 </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p class=\"mobile-menu-close\">\r\n");
      out.write("               <button>\r\n");
      out.write("                  <span class=\"blind\">메뉴닫기</span>\r\n");
      out.write("                  <span></span>\r\n");
      out.write("                  <span></span>\r\n");
      out.write("               </button>\r\n");
      out.write("            </p>\r\n");
      out.write("         </div>\r\n");
      out.write("      </header>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
 
	ArrayList<Board> list = (ArrayList<Board>)request.getAttribute("list");
   	ArrayList<Board> listtwo = (ArrayList<Board>)request.getAttribute("listtwo");       
	
     
   

      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources\\css\\main.css\">\r\n");
      out.write("<script src=\"resources\\js\\jquery.js\"></script>\r\n");
      out.write("<script src=\"resources\\js\\jquery.bxslider.min.js\"></script>\r\n");
      out.write("<script src=\"resources\\js\\isotope.pkgd.min.js\"></script>\r\n");
      out.write("<script src=\"resources\\js\\main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!--콘테이너 영역-->\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<section id=\"main-visual\" class=\"rounded\">\r\n");
      out.write("			<h3 class=\"blind\">HOT BOOK</h3>\r\n");
      out.write("			<ul class=\"main-visual-slide\">\r\n");
      out.write("			");
for(Board b : listtwo){ 
      out.write("\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"visual-item-wrap item1\">\r\n");
      out.write("					<img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/board_upfiles/");
      out.print(b.getTitleImg()  );
      out.write("\">\r\n");
      out.write("					<h4 class=\"visual-title\"> &lt;");
      out.print(b.getBoardTitle() );
      out.write("&gt;</h4>\r\n");
      out.write("					<p>\r\n");
      out.write("					<span> ");
      out.print(b.getBoardContent() );
      out.write("</span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"detail-view\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/detailuser.th?bNo=");
      out.print(b.getBoardNo() );
      out.write("\">자세히 보기</a></p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("			 	");
} 
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</section>\r\n");
      out.write("		<section id=\"notice-tab-wrap\" class=\"rounded\">\r\n");
      out.write("			<h3 class=\"sec-tit-1\">NOTICE &amp; NEWS</h3>\r\n");
      out.write("			<h4 class=\"tab-btn-1\"><a href=\"#\" class=\"on\">공지사항</a></h4>\r\n");
      out.write("			<div class=\"tab-container-1\">\r\n");
      out.write("				<ul>	\r\n");
      out.write("					<li><a href=\"#\">공지사항 관련된 내용입니다.</a><span>2017.08.07</span></li>\r\n");
      out.write("					<li><a href=\"#\">공지사항 관련된 내용입니다.</a><span>2017.08.07</span></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<p class=\"icon-more\"><a href=\"#\">more</a></p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<h4 class=\"tab-btn-2\"><a href=\"#\">새소식</a></h4>\r\n");
      out.write("			<div class=\"tab-container-2\">\r\n");
      out.write("				<p class=\"no-write\">등록된 내용이 없습니다.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<section id=\"best-book-wrap\">\r\n");
      out.write("			<h3 class=\"sec-tit-1\">BEST BOOK</h3>\r\n");
      out.write("			<ul class=\"best-book-list grid\">\r\n");
      out.write("				<li class=\"grid-item\">\r\n");
      out.write("					<p><a href=\"#\">  </a></p>\r\n");
      out.write("					<p><a href=\"#\"><img src=\"resources\\images\\main\\3.jpg\" alt=\"\"></a></p>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"grid-item\">\r\n");
      out.write("					<a href=\"#\"><img src=\"resources\\images\\main\\3.jpg\" alt=\"\"></a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"grid-item\">\r\n");
      out.write("					<p><a href=\"#\"><img src=\"Wresources\\images\\main\\3.jpg\" alt=\"\"></a></p>\r\n");
      out.write("					<p><a href=\"#\"><img src=\"resources\\images\\main\\3.jpg\" alt=\"\"></a></p>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"grid-item\">\r\n");
      out.write("						<a href=\"#\"><img src=\"resources\\images\\main\\3.jpg\" alt=\"\"></a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</section>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"..\\..\\resources\\css\\main.css\">\r\n");
      out.write("<script src=\"..\\..\\resources\\js\\jquery.js\"></script>\r\n");
      out.write("<script src=\"..\\..\\resources\\js\\jquery.bxslider.min.js\"></script>\r\n");
      out.write("<script src=\"..\\..\\resources\\js\\isotope.pkgd.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"..\\..\\resources\\js\\main.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"footer-wrap\">\r\n");
      out.write("		<footer id=\"footer\">\r\n");
      out.write("			<small>Copyright&copy;2040 사구팔구㈜ EasySellnice Co., Ltd. All Rights Reserved</small>\r\n");
      out.write("		</footer>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--//푸터 영역-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
