/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-08-25 09:41:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.kh.team3.member.model.vo.*;

public final class createUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.kh.team3.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");


	ArrayList<Member> list = (ArrayList<Member>)request.getAttribute("list");





      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Document</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <link href=\"resources\\css\\create.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(" #id{\n");
      out.write("        margin-left: 105px;\n");
      out.write("     }\n");
      out.write("\n");
      out.write("     #idCheckBtn{\n");
      out.write("         width: 100px;\n");
      out.write("         height: 45px;\n");
      out.write("     }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"all\">\n");
      out.write("\n");
      out.write("    <div class=\"top\"  >\n");
      out.write("\n");
      out.write("        <img src=\"resources\\images\\common\\logo2.png\" id=\"logo\">\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("   \n");
      out.write("	<form id=\"createUser\" method=\"post\"  action=\"");
      out.print(request.getContextPath() );
      out.write("/insert.me\"\n");
      out.write("			 onSubmit=\"return joinValidate();\">\n");
      out.write("\n");
      out.write("\n");
      out.write("      	<input type=\"text\"  id=\"id\" name=\"id\" placeholder=\"아이디\" maxlength=\"13\" required> \n");
      out.write("      	<button type=\"button\" id=\"idCheckBtn\" onclick=\"checkId();\">중복 확인 </button>\n");
      out.write("      	 <br>\n");
      out.write("    	   <span id=\"idspan\"></span>  \n");
      out.write("        <br>\n");
      out.write("    	\n");
      out.write("        <input type=\"password\" id=\"pwd\" name=\"pw\" placeholder=\"비밀번호\">  <br>  \n");
      out.write("           <span id=\"pwspan\"></span>  \n");
      out.write("        <br>\n");
      out.write("        \n");
      out.write("      \n");
      out.write("        <input type=\"password\" id=\"pwdcheck\" name=\"pw2\" placeholder=\"비밀번호확인\">   <br> \n");
      out.write("           <span id=\"pwspan2\"> </span> \n");
      out.write("        <br>\n");
      out.write("        \n");
      out.write("    \n");
      out.write("        <input type=\"text\" id=\"name\" name=\"name\" placeholder=\"이름\">    <br>\n");
      out.write("           <span id=\"namespan\"></span>  \n");
      out.write("        <br>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <input type=\"text\" id=\"phone\" name=\"phone\" placeholder=\"핸드폰 반호\">    <br>\n");
      out.write("         <span id=\"phonespan\"></span>  \n");
      out.write("        <br>\n");
      out.write("      \n");
      out.write("        \n");
      out.write("       \n");
      out.write("        <input type=\"text\" id=\"nickname\" name=\"nickname\" placeholder=\"닉네임\">  <br>  \n");
      out.write("   <span id=\"nickspan\"></span>  \n");
      out.write("        <br>\n");
      out.write("\n");
      out.write("        <input type=\"text\" id=\"address\" name=\"address\"  placeholder=\"주소\">  <br>  \n");
      out.write("        \n");
      out.write("        <label>카테고리 선택 :  </label>\n");
      out.write("        <select id=\"select\" name=\"gory\">\n");
      out.write("            \n");
      out.write("            <option value=\"1\">태블릿</option>\n");
      out.write("            <option value=\"2\">데스크탑</option>\n");
      out.write("            <option value=\"3\">핸드폰</option>\n");
      out.write("            <option value=\"4\">기타</option>\n");
      out.write("\n");
      out.write("\n");
      out.write("        </select>\n");
      out.write("        <br>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <input type=\"submit\" value=\"로그인\" id=\"path\">\n");
      out.write("\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"footer\">\n");
      out.write("      \n");
      out.write("        <a href=\"\" id=\"idfind\">이용약관</a>\n");
      out.write("        <span> | </span>\n");
      out.write("        <a href=\"\" id=\"pwdfind\">중고거래 주의사항</a>\n");
      out.write("        <span> | </span>    \n");
      out.write("        <a href=\"\" id=\"pwdfind\">중고거래 법적사항</a>\n");
      out.write("        <span> | </span>    \n");
      out.write("        <a href=\"\" id=\"pwdfind\">고객센터</a>\n");
      out.write("        \n");
      out.write("        <br>\n");
      out.write("        <div class=\"footer2\">\n");
      out.write("            <img src=\"resources\\images\\common\\logo2.png\" id=\"footerimg\">\n");
      out.write("            Copyright All Rights Reserved.\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("function joinValidate(){\n");
      out.write("	\n");
      out.write("\n");
      out.write("	\n");
      out.write("	if(!(/^[a-z][a-z\\d]{3,11}$/i.test($(\"#createUser input[name=id]\").val()))){\n");
      out.write("		$(\"#createUser input[name=userId]\").focus();\n");
      out.write("        return false;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	if($(\"#createUser input[name=pw]\").val() != $(\"#createUser input[name=pw2]\").val()){\n");
      out.write("		$(\"#pwspan\").text(\"비밀번호와 확인이 일치하지 않습니다.\").css(\"color\", \"red\");\n");
      out.write("		$(\"#pwspan2\").text(\"비밀번호와 확인이 일치하지 않습니다.\").css(\"color\", \"red\");\n");
      out.write("		\n");
      out.write("		return false;			\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	 if(!(/^[가-힣]{2,}$/.test($(\"#createUser input[name=name]\").val()))){\n");
      out.write("		 $(\"#createUser input[name=name]\").focus();\n");
      out.write("        return false;\n");
      out.write("	 }\n");
      out.write("	 \n");
      out.write("	 return true;\n");
      out.write("	\n");
      out.write("	\n");
      out.write("}\n");
      out.write("\n");
      out.write("function checkId(){\n");
      out.write("    var userId = $(\"#createUser input[name=id]\");\n");
      out.write("    if(userId.val() ==\"\"){ //값이 없다면\n");
      out.write("       alert(\"아이디를 입력해주세요\");\n");
      out.write("       return false;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    $.ajax({ // 값이 있다면 ajax를 통해\n");
      out.write("       url:\"idCheck.me\",\n");
      out.write("       type:\"post\",\n");
      out.write("       data: {userId : userId.val()},\n");
      out.write("       success:function(result){\n");
      out.write("          if(result ==\"fail\"){\n");
      out.write("             alert(\"사용할수 없는 아이디 입니다\");\n");
      out.write("             userId.focus();\n");
      out.write("          }else{\n");
      out.write("             if(confirm(\"사용가능한 아이디입니다. 사용하시겠습니까?\")){\n");
      out.write("                userId.attr(\"readonly\", \"true\");\n");
      out.write("                $(\"#idCheckBtn\").attr(\"disabled\");\n");
      out.write("             }else{\n");
      out.write("                userId.focus();\n");
      out.write("             }\n");
      out.write("          }\n");
      out.write("       },\n");
      out.write("       error:function(){\n");
      out.write("          console.log(\"서버통신실패\");\n");
      out.write("       }\n");
      out.write("    })\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
